import sys
num = int(sys.argv[1])
print("#include <iostream>")
print("#include \"IntArray.h\"")
print("using namespace std;")
print(f"extern void multiplyBy{num}(IntArray *p);")
print("int main() {")
print("    IntArray* arr = new IntArray();")
print("    arr->elements = new int[7]{6, 7, 4, 2, 0, 6, 9};")
print("    arr->size = 7;")
print("    cout << arr->stringify();")
print(f"    multiplyBy{num}(arr);")
print("    cout << arr->stringify();")
print("    delete arr;")
print("    arr = nullptr;")
print("    return 0;")
print("}")